# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MCLABDemo01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MCLABDemo01
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'

  # Pods for camera
  pod 'ImagePicker'

  # Pods for loading animate
  pod 'RSLoadingView'
end
